# espanso configuration file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the global configuration options for espanso.
# These are the parameters that will be used by default on every application,
# but you can also override them on a per-application basis.

# To make customization easier, this file contains some of the commonly used
# parameters. Feel free to uncomment and tune them to fit your needs!

# --- Toggle key

# Customize the key used to disable and enable espanso (when double tapped)
# Available options: CTRL, SHIFT, ALT, CMD, OFF
# You can also specify the key variant, such as LEFT_CTRL, RIGHT_SHIFT, etc...
toggle_key: ALT
# You can also disable the toggle key completely with
# toggle_key: OFF

# --- Injection Backend

# Espanso supports multiple ways of injecting text into applications. Each of
# them has its quirks, therefore you may want to change it if you are having problems.
# By default, espanso uses the "Auto" backend which should work well in most cases,
# but you may want to try the "Clipboard" or "Inject" backend in case of issues.
# backend: Clipboard

# --- Auto-restart

# Enable/disable the config auto-reload after a file change is detected.
auto_restart: true

# --- Clipboard threshold

# Because injecting long texts char-by-char is a slow operation, espanso automatically
# uses the clipboard if the text is longer than 'clipboard_threshold' characters.
# clipboard_threshold: 100

# For a list of all the available options, visit the official docs at: https://espanso.org/docs/

# --- Search Shortcut

# Customizing the search shortcut
# If you don't like the default Alt+Space shortcut, you can change it by adding the following line to your $CONFIG/config/default.yml file:
# search_shortcut: ALT+SPACE

# --- Search Trigger

# Customizing the search trigger
# The search bar can also be configured to be shown after typing a trigger. For example, you might tune it to be displayed after typing .search by adding this option:
# search_trigger: off
search_trigger: ";;"

# --- Icon
# You can hide the Espanso status icon on macOS and Windows by adding the following option to your $CONFIG/config/default.yml file:
show_icon: true

# --- Notifications
# You can hide the notifications by adding the following option to your $CONFIG/config/default.yml config:
show_notifications: true
# --- Other Options
# https://espanso.org/docs/configuration/options/#options-reference

# Clipboard, Inject, Auto
backend: Auto

# Number of milliseconds between text injection events
# inject_delay: 0

# Number of milliseconds between key injection events.
# key_delay: 0

# Number of chars after which a match is injected with the clipboard backend instead of the default one.
clipboard_threshold: 100

# If true, Espanso will attempt to preserve the previous clipboard content after an expansion has taken place.
preserve_clipboard: true

# When enabled, espanso automatically "reverts" an expansion if the user presses the Backspace key afterwards.
# This is not available on some platform/configurations
undo_backspace: false
